### ISSUE TITLE
[Bug] BigInt type with default value

### ISSUE THREAD

**Issue by hankyungs** [kimjbstar/prisma-class-generator#16]
Hello.

I'm using MS-SQL.
I got an error for type BigInt with default value.

error:
error TS2322: Type 'number' is not assignable to type 'BigInt'.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/41785064/191399133-8fb4a390-a1c6-44f0-8425-173a9361b3a6.png">

If I change the generated code to
AGROUP_NO: BigInt = BigInt(1);

then error is disappeared

## Specifications

-   Version:
-   Prisma Version: 4.3.1
-   Platform: NestJs, MS-SQL

**Comment by kimjbstar** [comment]
Thanks for the report.

this bug has fixed by https://github.com/kimjbstar/prisma-class-generator/commit/77598359f0a70e9e3a07fbd65dba98085ebff276
