### ISSUE TITLE
Prisma version limit

### ISSUE THREAD

**Issue by happy1836** [kimjbstar/prisma-class-generator#2]
hi ，
Prisma version limit，when i use prisma 3.2.1 Latest， it can not create _gen folder and related files .tks

**Comment by kimjbstar** [comment]
Hello, happy1836.

I tested it with that version, but it was impossible to reproduce the issue. 😢 

I think I need more information to solve this issue.
For example, whether it is simply not generated, an error message appears, or is not generated as intended.

**Comment by happy1836** [comment]
hi，pls update on npm latest，and can support @Field() for @nestjs/graphql first?  thank you very mush.
