### ISSUE TITLE
Invalid import path generation with pnpm

### ISSUE THREAD

**Issue by ngregrichardson** [kimjbstar/prisma-class-generator#23]
## Expected Behavior

```typescript
import { Role } from '../../node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client';
```

or

```typescript
import { Role } from '..\\..\\node_modules\\.pnpm\\@prisma+client@4.8.1_prisma@4.8.1\\node_modules\\@prisma\\client';
```

## Actual Behavior

```typescript
import { Role } from '....\node_modules.pnpm@prisma+client@4.8.1_prisma@4.8.1\node_modules@prismaclient';
```

## Steps to Reproduce the Problem

I'm doing this on Windows and cannot get it to reproduce minimally on CodeSandbox (which I'd assume is Linux).

1. Clone the `prisma-class-generator` repository on a Windows machine.
2. Install dependencies.
3. Run `yarn generate:postgresql`.
4. See invalid import in generated `product.ts`.

## Specifications

-   Version: v0.2.5
-   Prisma Version: v4.9.0
-   Platform: Windows/Node.js

## Solution
I don't think this should be too bad of a fix, I think the easiest would be to add something like

```typescript
importRow.from = importRow.from.replaceAll('\\', '/')
```

right above https://github.com/kimjbstar/prisma-class-generator/blob/c5073a3356b50d279f2f8861b5ff4ed5219041dc/src/generator.ts#L147

I'm not sure how well this would play with other operating systems, so maybe something like

```typescript
importRow.from = importRow.from.replaceAll('\\', '\\\\')
```

to replace with a double slash. If either of these would work, I'd be happy to make a PR.

**Comment by Antoxa1081** [comment]
Same problem on Platform: Windows/Node.js using default npm

**Comment by kimjbstar** [comment]
In the process of creating the prisma client import path, unnecessary logic was found and removed.

From now on, this path is set to "@prisma/client" by default, and can be specified directly using the **"clientImportPath"** option.
