### ISSUE TITLE
extraModels: [...PrismaModel.extraModels] does not work

### ISSUE THREAD

**Issue by moh1434** [kimjbstar/prisma-class-generator#32]
I have:
```
import { User } from '@prisma/client';
import { User as UserClass } from './_gen/prisma-class/user';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get('/users')
  async getAll(): Promise<User[]> {
    return (await this.appService.getAll()) as User[];
  }

  @Get('/users2')
  async getAll2(): Promise<UserClass[]> {
    return await this.appService.getAll();
  }
}
```
And in main.ts:
 ```
 const options = new DocumentBuilder()
    .setTitle('nest example')
    .setDescription('My nest API description')
    .setVersion('1.0')
    .addTag('myTag')
    .build();

  const document = SwaggerModule.createDocument(app, options, {
    extraModels: [...PrismaModel.extraModels],
  });

  SwaggerModule.setup('api', app, document);
```
## Expected Behavior
I expected swagger will display description response schema for both `/users` and `/users2`
## Actual Behavior
![result_user](https://user-images.githubusercontent.com/61632563/236157037-eee7bd00-fca5-491d-969e-4dbfa8d4a0b4.png)

![result_user2](https://user-images.githubusercontent.com/61632563/236157064-ef9c80ed-5183-45cc-b19b-75397ebb4f11.png)
swagger works only for the explicitly imported generated class.

## Steps to Reproduce the Problem

 Clone [This Repo](https://github.com/moh1434/prisma-class-generator-try) and see [localhost:300/api](http://localhost:3000/api).

## Specifications

-   "prisma-class-generator": "^0.2.6"
-  "@nestjs/swagger": "^6.3.0"
-   Prisma Version: "prisma": "^4.11.0"
-   Platform: mac m1

**Comment by WilliamBlais** [comment]
@moh1434 You need to decorate your Controller.

For example,

```
  @ApiOkResponse({ type: UserClass, isArray:true })
  @Get('/users2')
  async getAll2(): Promise<UserClass[]> {
    return await this.appService.getAll();
  }
```
