### ISSUE TITLE
Json type generates a field with object type instead of Prisma.JsonValue

### ISSUE THREAD

**Issue by icarogtavares** [kimjbstar/prisma-class-generator#36]
## Expected Behavior
Field must have `Prisma.JsonValue` type

## Actual Behavior
Field has `object` type

## Steps to Reproduce the Problem
1. Create a table with Json type
1. Run `npx prisma generate`
1. Verify the generated file for this model

Example: 
```
model AnyModel {
  id       Int @id @default(autoincrement())
  anyField Json     @default("{}")
}
```

## Specifications

-   Version: 0.2.6
-   Prisma Version: 4.15.0
-   Platform: Windows 10 Version 22H2 (19045.3155)

**Comment by gmanavarro** [comment]
@kimjbstar is there any plans on solving this issue? thanks!
