### ISSUE TITLE
No Files Generated

### ISSUE THREAD

**Issue by cbwilliamsnh** [kimjbstar/prisma-class-generator#42]
## Expected Behavior
class files generated to "./../src/backplane/generated"

## Actual Behavior
Classes generated but only printed in standard output, so I had to manually create the class files via copy and paste.

## Steps to Reproduce the Problem

1. Install the generator
2. Run "npx prisma generate"

## Specifications

-   Version: latest
-   Prisma Version: lastest
-   Platform: MacOS Ventura 13.4.1

**Comment by bernikson** [comment]
having same issue

**Comment by jannis6023** [comment]
Try setting the config value `dryRun` to false
