### ISSUE TITLE
The folder _gen isn't created

### ISSUE THREAD

**Issue by MML1357** [kimjbstar/prisma-class-generator#5]
## Expected Behavior
The folder _gen is created
## Actual Behavior
The folder _gen isn't created
## Steps to Reproduce the Problem

1. Install it
2. Configure prisma.schema
2. Execute npx prisma generate

## Specifications

-   Version: 0.1.10
-   Prisma Version: 3.6.0
-   Platform: Linux

**Comment by MML1357** [comment]
option dryRun wasn't set to false

**Comment by mad-zephyr** [comment]
> option dryRun wasn't set to false

Hello, the same I have the problem. Could you write please how to set dryRun option to false?

**Comment by mad-zephyr** [comment]
solved... I found example in  https://github.com/kimjbstar/prisma-class-generator/tree/main/prisma
