### ISSUE TITLE
Optional properties in generated classes don't match Prisma generated types

### ISSUE THREAD

**Issue by gmanavarro** [kimjbstar/prisma-class-generator#67]
Hi, I'm running into a couple of errors due to type mismatch between prisma-class-generator classes and Prisma generated types. I'm using Typescript with `strictNullChecks` activated and `null` and `undefined` are not equivalent.  

## Actual behavior
When you declare a prisma model like this: 
```prisma
model Document {
  id       String           @id @default(uuid())
  name     String
  url      String?
```

The resulting class is generated like this:
```ts
export class Document {
  @ApiProperty({ type: String })
  id: string;

  @ApiProperty({ type: String })
  name: string;

  @ApiProperty({ type: String })
  url?: string;
```

## Expected behavior
To properly match Prisma generated typings for all optional properties in models, the resulting class should be generated like this: 

```ts
export class Document {
  @ApiProperty({ type: String })
  id: string;

  @ApiProperty({ type: String })
  name: string;

  @ApiProperty({ type: String })
  url: string | null;
```

**Comment by muhammadyusuf-kurbonov** [comment]
How you fix that?
